name: Deploy to EC2 Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (default = latest or commit SHA)"
        required: false
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export KUBECONFIG=/home/ec2-user/.kube/config

            IMAGE=pratikpatel8982/manufacturing-agent:${{ github.event.inputs.image_tag }}

            echo "Deploying image: $IMAGE"

            docker pull $IMAGE

            kubectl set image deployment/manufacturing-agent-deployment \
            manufacturing-agent=$IMAGE

            kubectl rollout status deployment/manufacturing-agent-deployment